### ISSUE TITLE
from model import Classifier, Inversion

### ISSUE THREAD

**Issue by claire8967** [katekemu/model_inversion_defense#1]
I recently use this github to simulate model inversion.
However,when I try to implement MIDAS_deep.ipynb,I have problem that I can not import Classifier and Inversion successfully because I can not find the "model" file.
Please tell me how to solve this problem.
Thanks !

**Comment by katekemu** [comment]
Please refer to README.

> Please download the [trained classifier and inversion model](https://drive.google.com/drive/folders/12TgsgytXNE76FUCd74nSOmpIn8n9TVSd?usp=sharing) and save them in results/deep/.

**Comment by claire8967** [comment]
Sorry, I am not familiar with .pth file enough.
Can I use the .pth file to retrain the model ?


katekemu ***@***.***>於 2023年4月24日 週一，下午8:02寫道：

**Comment by claire8967** [comment]
I have already download the trained classifier and inversion model
<https://drive.google.com/drive/folders/12TgsgytXNE76FUCd74nSOmpIn8n9TVSd?usp=sharing>
and
save them in results/deep/,
but I still can not find the module "model",
and I can not train the model with Classifier and Inversion,
Could you give me some hint to solve this problem?

吳苡菡 ***@***.***> 於 2023年4月24日 週一 下午8:13寫道：

**Comment by katekemu** [comment]
Sorry for misunderstanding your question. For the code about the class Classifier and and Inversion, please refer to the paper "Neural Network Inversion in Adversarial Setting via Background Knowledge Alignment" and their [github code](https://github.com/yziqi/adversarial-model-inversion).

**Comment by claire8967** [comment]
Thanks!

katekemu ***@***.***> 於 2023年4月24日 週一 下午10:09寫道：
